### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by mparaz** [awslabs/aws-apigateway-lambda-authorizer-blueprints#4]
Can we have some unit tests? The logic has quite a lot of conditions.

**Comment by jackrk** [comment]
I'd be happy to accept a PR, but I doubt I'll have time to add these in the near future.

**Comment by seantcanavan** [comment]
I'd probably be able to initialize a PR and share some of my unit tests but they're not passing at the moment. 
![screen shot 2017-04-27 at 11 40 21 am](https://cloud.githubusercontent.com/assets/6250751/25498873/6e1b22de-2b3e-11e7-8293-2c89a38cea32.png)

There's an IndexOutOfBoundsException when parsing sample ARN values from: http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-lambda

None of the sample Lambda ARN values correctly parse at the moment. Specifically, stage, httpMethod, and resource seem to be missing. 

Is that because those values are only added to the ARN when called on a live environment versus the non-live examples post on the ARN help page?

**Comment by JoeDM09** [comment]
@seantcanavan The arn is formatted specifically for Api Gateway. see http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-apigateway

**Comment by jackrk** [comment]
Closing, please reopen if anyone has a PR
